version: '3.8'

services:
  redis:
    container_name: conik-redis
    image: redis:7.0.11
    ports:
      - "6379:6379"
    networks:
      - conik_network

  postgres:
    container_name: conik-db
    image: postgres:14.17
    environment:
      POSTGRES_DB: conikdb
      POSTGRES_USER: conik
      POSTGRES_PASSWORD: conik7897
    ports:
      - "5432:5432"
    networks:
      - conik_network

networks:
  conik_network:
    driver: bridge
